# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/nova/Documents/c++ repo/mySFML_trash"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/nova/Documents/c++ repo/mySFML_trash"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/cpack --config ./CPackSourceConfig.cmake /Users/nova/Documents/c++\ repo/mySFML_trash/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/nova/Documents/c++ repo/mySFML_trash/CMakeFiles" "/Users/nova/Documents/c++ repo/mySFML_trash//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/nova/Documents/c++ repo/mySFML_trash/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ekzeckt

# Build rule for target.
Ekzeckt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ekzeckt
.PHONY : Ekzeckt

# fast build rule for target.
Ekzeckt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/build
.PHONY : Ekzeckt/fast

source/Content/ItemsStuff/Inventory.o: source/Content/ItemsStuff/Inventory.cpp.o
.PHONY : source/Content/ItemsStuff/Inventory.o

# target to build an object file
source/Content/ItemsStuff/Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/ItemsStuff/Inventory.cpp.o
.PHONY : source/Content/ItemsStuff/Inventory.cpp.o

source/Content/ItemsStuff/Inventory.i: source/Content/ItemsStuff/Inventory.cpp.i
.PHONY : source/Content/ItemsStuff/Inventory.i

# target to preprocess a source file
source/Content/ItemsStuff/Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/ItemsStuff/Inventory.cpp.i
.PHONY : source/Content/ItemsStuff/Inventory.cpp.i

source/Content/ItemsStuff/Inventory.s: source/Content/ItemsStuff/Inventory.cpp.s
.PHONY : source/Content/ItemsStuff/Inventory.s

# target to generate assembly for a file
source/Content/ItemsStuff/Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/ItemsStuff/Inventory.cpp.s
.PHONY : source/Content/ItemsStuff/Inventory.cpp.s

source/Content/Map/TileMap.o: source/Content/Map/TileMap.cpp.o
.PHONY : source/Content/Map/TileMap.o

# target to build an object file
source/Content/Map/TileMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/Map/TileMap.cpp.o
.PHONY : source/Content/Map/TileMap.cpp.o

source/Content/Map/TileMap.i: source/Content/Map/TileMap.cpp.i
.PHONY : source/Content/Map/TileMap.i

# target to preprocess a source file
source/Content/Map/TileMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/Map/TileMap.cpp.i
.PHONY : source/Content/Map/TileMap.cpp.i

source/Content/Map/TileMap.s: source/Content/Map/TileMap.cpp.s
.PHONY : source/Content/Map/TileMap.s

# target to generate assembly for a file
source/Content/Map/TileMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/Map/TileMap.cpp.s
.PHONY : source/Content/Map/TileMap.cpp.s

source/Content/Map/block.o: source/Content/Map/block.cpp.o
.PHONY : source/Content/Map/block.o

# target to build an object file
source/Content/Map/block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/Map/block.cpp.o
.PHONY : source/Content/Map/block.cpp.o

source/Content/Map/block.i: source/Content/Map/block.cpp.i
.PHONY : source/Content/Map/block.i

# target to preprocess a source file
source/Content/Map/block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/Map/block.cpp.i
.PHONY : source/Content/Map/block.cpp.i

source/Content/Map/block.s: source/Content/Map/block.cpp.s
.PHONY : source/Content/Map/block.s

# target to generate assembly for a file
source/Content/Map/block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/Map/block.cpp.s
.PHONY : source/Content/Map/block.cpp.s

source/Content/rotationCircle.o: source/Content/rotationCircle.cpp.o
.PHONY : source/Content/rotationCircle.o

# target to build an object file
source/Content/rotationCircle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/rotationCircle.cpp.o
.PHONY : source/Content/rotationCircle.cpp.o

source/Content/rotationCircle.i: source/Content/rotationCircle.cpp.i
.PHONY : source/Content/rotationCircle.i

# target to preprocess a source file
source/Content/rotationCircle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/rotationCircle.cpp.i
.PHONY : source/Content/rotationCircle.cpp.i

source/Content/rotationCircle.s: source/Content/rotationCircle.cpp.s
.PHONY : source/Content/rotationCircle.s

# target to generate assembly for a file
source/Content/rotationCircle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Content/rotationCircle.cpp.s
.PHONY : source/Content/rotationCircle.cpp.s

source/Core.o: source/Core.cpp.o
.PHONY : source/Core.o

# target to build an object file
source/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Core.cpp.o
.PHONY : source/Core.cpp.o

source/Core.i: source/Core.cpp.i
.PHONY : source/Core.i

# target to preprocess a source file
source/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Core.cpp.i
.PHONY : source/Core.cpp.i

source/Core.s: source/Core.cpp.s
.PHONY : source/Core.s

# target to generate assembly for a file
source/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/Core.cpp.s
.PHONY : source/Core.cpp.s

source/GUI/components/button.o: source/GUI/components/button.cpp.o
.PHONY : source/GUI/components/button.o

# target to build an object file
source/GUI/components/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/button.cpp.o
.PHONY : source/GUI/components/button.cpp.o

source/GUI/components/button.i: source/GUI/components/button.cpp.i
.PHONY : source/GUI/components/button.i

# target to preprocess a source file
source/GUI/components/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/button.cpp.i
.PHONY : source/GUI/components/button.cpp.i

source/GUI/components/button.s: source/GUI/components/button.cpp.s
.PHONY : source/GUI/components/button.s

# target to generate assembly for a file
source/GUI/components/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/button.cpp.s
.PHONY : source/GUI/components/button.cpp.s

source/GUI/components/dropDownList.o: source/GUI/components/dropDownList.cpp.o
.PHONY : source/GUI/components/dropDownList.o

# target to build an object file
source/GUI/components/dropDownList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/dropDownList.cpp.o
.PHONY : source/GUI/components/dropDownList.cpp.o

source/GUI/components/dropDownList.i: source/GUI/components/dropDownList.cpp.i
.PHONY : source/GUI/components/dropDownList.i

# target to preprocess a source file
source/GUI/components/dropDownList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/dropDownList.cpp.i
.PHONY : source/GUI/components/dropDownList.cpp.i

source/GUI/components/dropDownList.s: source/GUI/components/dropDownList.cpp.s
.PHONY : source/GUI/components/dropDownList.s

# target to generate assembly for a file
source/GUI/components/dropDownList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/dropDownList.cpp.s
.PHONY : source/GUI/components/dropDownList.cpp.s

source/GUI/components/minimap.o: source/GUI/components/minimap.cpp.o
.PHONY : source/GUI/components/minimap.o

# target to build an object file
source/GUI/components/minimap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/minimap.cpp.o
.PHONY : source/GUI/components/minimap.cpp.o

source/GUI/components/minimap.i: source/GUI/components/minimap.cpp.i
.PHONY : source/GUI/components/minimap.i

# target to preprocess a source file
source/GUI/components/minimap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/minimap.cpp.i
.PHONY : source/GUI/components/minimap.cpp.i

source/GUI/components/minimap.s: source/GUI/components/minimap.cpp.s
.PHONY : source/GUI/components/minimap.s

# target to generate assembly for a file
source/GUI/components/minimap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/minimap.cpp.s
.PHONY : source/GUI/components/minimap.cpp.s

source/GUI/components/progressBar.o: source/GUI/components/progressBar.cpp.o
.PHONY : source/GUI/components/progressBar.o

# target to build an object file
source/GUI/components/progressBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/progressBar.cpp.o
.PHONY : source/GUI/components/progressBar.cpp.o

source/GUI/components/progressBar.i: source/GUI/components/progressBar.cpp.i
.PHONY : source/GUI/components/progressBar.i

# target to preprocess a source file
source/GUI/components/progressBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/progressBar.cpp.i
.PHONY : source/GUI/components/progressBar.cpp.i

source/GUI/components/progressBar.s: source/GUI/components/progressBar.cpp.s
.PHONY : source/GUI/components/progressBar.s

# target to generate assembly for a file
source/GUI/components/progressBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/progressBar.cpp.s
.PHONY : source/GUI/components/progressBar.cpp.s

source/GUI/components/selector.o: source/GUI/components/selector.cpp.o
.PHONY : source/GUI/components/selector.o

# target to build an object file
source/GUI/components/selector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/selector.cpp.o
.PHONY : source/GUI/components/selector.cpp.o

source/GUI/components/selector.i: source/GUI/components/selector.cpp.i
.PHONY : source/GUI/components/selector.i

# target to preprocess a source file
source/GUI/components/selector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/selector.cpp.i
.PHONY : source/GUI/components/selector.cpp.i

source/GUI/components/selector.s: source/GUI/components/selector.cpp.s
.PHONY : source/GUI/components/selector.s

# target to generate assembly for a file
source/GUI/components/selector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/selector.cpp.s
.PHONY : source/GUI/components/selector.cpp.s

source/GUI/components/staticSelector.o: source/GUI/components/staticSelector.cpp.o
.PHONY : source/GUI/components/staticSelector.o

# target to build an object file
source/GUI/components/staticSelector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/staticSelector.cpp.o
.PHONY : source/GUI/components/staticSelector.cpp.o

source/GUI/components/staticSelector.i: source/GUI/components/staticSelector.cpp.i
.PHONY : source/GUI/components/staticSelector.i

# target to preprocess a source file
source/GUI/components/staticSelector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/staticSelector.cpp.i
.PHONY : source/GUI/components/staticSelector.cpp.i

source/GUI/components/staticSelector.s: source/GUI/components/staticSelector.cpp.s
.PHONY : source/GUI/components/staticSelector.s

# target to generate assembly for a file
source/GUI/components/staticSelector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/staticSelector.cpp.s
.PHONY : source/GUI/components/staticSelector.cpp.s

source/GUI/components/textbox.o: source/GUI/components/textbox.cpp.o
.PHONY : source/GUI/components/textbox.o

# target to build an object file
source/GUI/components/textbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/textbox.cpp.o
.PHONY : source/GUI/components/textbox.cpp.o

source/GUI/components/textbox.i: source/GUI/components/textbox.cpp.i
.PHONY : source/GUI/components/textbox.i

# target to preprocess a source file
source/GUI/components/textbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/textbox.cpp.i
.PHONY : source/GUI/components/textbox.cpp.i

source/GUI/components/textbox.s: source/GUI/components/textbox.cpp.s
.PHONY : source/GUI/components/textbox.s

# target to generate assembly for a file
source/GUI/components/textbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/textbox.cpp.s
.PHONY : source/GUI/components/textbox.cpp.s

source/GUI/components/textureSelector.o: source/GUI/components/textureSelector.cpp.o
.PHONY : source/GUI/components/textureSelector.o

# target to build an object file
source/GUI/components/textureSelector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/textureSelector.cpp.o
.PHONY : source/GUI/components/textureSelector.cpp.o

source/GUI/components/textureSelector.i: source/GUI/components/textureSelector.cpp.i
.PHONY : source/GUI/components/textureSelector.i

# target to preprocess a source file
source/GUI/components/textureSelector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/textureSelector.cpp.i
.PHONY : source/GUI/components/textureSelector.cpp.i

source/GUI/components/textureSelector.s: source/GUI/components/textureSelector.cpp.s
.PHONY : source/GUI/components/textureSelector.s

# target to generate assembly for a file
source/GUI/components/textureSelector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/GUI/components/textureSelector.cpp.s
.PHONY : source/GUI/components/textureSelector.cpp.s

source/entitys/AI/AIAttack.o: source/entitys/AI/AIAttack.cpp.o
.PHONY : source/entitys/AI/AIAttack.o

# target to build an object file
source/entitys/AI/AIAttack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIAttack.cpp.o
.PHONY : source/entitys/AI/AIAttack.cpp.o

source/entitys/AI/AIAttack.i: source/entitys/AI/AIAttack.cpp.i
.PHONY : source/entitys/AI/AIAttack.i

# target to preprocess a source file
source/entitys/AI/AIAttack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIAttack.cpp.i
.PHONY : source/entitys/AI/AIAttack.cpp.i

source/entitys/AI/AIAttack.s: source/entitys/AI/AIAttack.cpp.s
.PHONY : source/entitys/AI/AIAttack.s

# target to generate assembly for a file
source/entitys/AI/AIAttack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIAttack.cpp.s
.PHONY : source/entitys/AI/AIAttack.cpp.s

source/entitys/AI/AIComponent.o: source/entitys/AI/AIComponent.cpp.o
.PHONY : source/entitys/AI/AIComponent.o

# target to build an object file
source/entitys/AI/AIComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIComponent.cpp.o
.PHONY : source/entitys/AI/AIComponent.cpp.o

source/entitys/AI/AIComponent.i: source/entitys/AI/AIComponent.cpp.i
.PHONY : source/entitys/AI/AIComponent.i

# target to preprocess a source file
source/entitys/AI/AIComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIComponent.cpp.i
.PHONY : source/entitys/AI/AIComponent.cpp.i

source/entitys/AI/AIComponent.s: source/entitys/AI/AIComponent.cpp.s
.PHONY : source/entitys/AI/AIComponent.s

# target to generate assembly for a file
source/entitys/AI/AIComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIComponent.cpp.s
.PHONY : source/entitys/AI/AIComponent.cpp.s

source/entitys/AI/AIFollow.o: source/entitys/AI/AIFollow.cpp.o
.PHONY : source/entitys/AI/AIFollow.o

# target to build an object file
source/entitys/AI/AIFollow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIFollow.cpp.o
.PHONY : source/entitys/AI/AIFollow.cpp.o

source/entitys/AI/AIFollow.i: source/entitys/AI/AIFollow.cpp.i
.PHONY : source/entitys/AI/AIFollow.i

# target to preprocess a source file
source/entitys/AI/AIFollow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIFollow.cpp.i
.PHONY : source/entitys/AI/AIFollow.cpp.i

source/entitys/AI/AIFollow.s: source/entitys/AI/AIFollow.cpp.s
.PHONY : source/entitys/AI/AIFollow.s

# target to generate assembly for a file
source/entitys/AI/AIFollow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIFollow.cpp.s
.PHONY : source/entitys/AI/AIFollow.cpp.s

source/entitys/AI/AISearchRing.o: source/entitys/AI/AISearchRing.cpp.o
.PHONY : source/entitys/AI/AISearchRing.o

# target to build an object file
source/entitys/AI/AISearchRing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AISearchRing.cpp.o
.PHONY : source/entitys/AI/AISearchRing.cpp.o

source/entitys/AI/AISearchRing.i: source/entitys/AI/AISearchRing.cpp.i
.PHONY : source/entitys/AI/AISearchRing.i

# target to preprocess a source file
source/entitys/AI/AISearchRing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AISearchRing.cpp.i
.PHONY : source/entitys/AI/AISearchRing.cpp.i

source/entitys/AI/AISearchRing.s: source/entitys/AI/AISearchRing.cpp.s
.PHONY : source/entitys/AI/AISearchRing.s

# target to generate assembly for a file
source/entitys/AI/AISearchRing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AISearchRing.cpp.s
.PHONY : source/entitys/AI/AISearchRing.cpp.s

source/entitys/AI/AIWander.o: source/entitys/AI/AIWander.cpp.o
.PHONY : source/entitys/AI/AIWander.o

# target to build an object file
source/entitys/AI/AIWander.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIWander.cpp.o
.PHONY : source/entitys/AI/AIWander.cpp.o

source/entitys/AI/AIWander.i: source/entitys/AI/AIWander.cpp.i
.PHONY : source/entitys/AI/AIWander.i

# target to preprocess a source file
source/entitys/AI/AIWander.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIWander.cpp.i
.PHONY : source/entitys/AI/AIWander.cpp.i

source/entitys/AI/AIWander.s: source/entitys/AI/AIWander.cpp.s
.PHONY : source/entitys/AI/AIWander.s

# target to generate assembly for a file
source/entitys/AI/AIWander.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/AI/AIWander.cpp.s
.PHONY : source/entitys/AI/AIWander.cpp.s

source/entitys/Enemys/slime.o: source/entitys/Enemys/slime.cpp.o
.PHONY : source/entitys/Enemys/slime.o

# target to build an object file
source/entitys/Enemys/slime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/Enemys/slime.cpp.o
.PHONY : source/entitys/Enemys/slime.cpp.o

source/entitys/Enemys/slime.i: source/entitys/Enemys/slime.cpp.i
.PHONY : source/entitys/Enemys/slime.i

# target to preprocess a source file
source/entitys/Enemys/slime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/Enemys/slime.cpp.i
.PHONY : source/entitys/Enemys/slime.cpp.i

source/entitys/Enemys/slime.s: source/entitys/Enemys/slime.cpp.s
.PHONY : source/entitys/Enemys/slime.s

# target to generate assembly for a file
source/entitys/Enemys/slime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/Enemys/slime.cpp.s
.PHONY : source/entitys/Enemys/slime.cpp.s

source/entitys/entity.o: source/entitys/entity.cpp.o
.PHONY : source/entitys/entity.o

# target to build an object file
source/entitys/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/entity.cpp.o
.PHONY : source/entitys/entity.cpp.o

source/entitys/entity.i: source/entitys/entity.cpp.i
.PHONY : source/entitys/entity.i

# target to preprocess a source file
source/entitys/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/entity.cpp.i
.PHONY : source/entitys/entity.cpp.i

source/entitys/entity.s: source/entitys/entity.cpp.s
.PHONY : source/entitys/entity.s

# target to generate assembly for a file
source/entitys/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/entity.cpp.s
.PHONY : source/entitys/entity.cpp.s

source/entitys/player.o: source/entitys/player.cpp.o
.PHONY : source/entitys/player.o

# target to build an object file
source/entitys/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/player.cpp.o
.PHONY : source/entitys/player.cpp.o

source/entitys/player.i: source/entitys/player.cpp.i
.PHONY : source/entitys/player.i

# target to preprocess a source file
source/entitys/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/player.cpp.i
.PHONY : source/entitys/player.cpp.i

source/entitys/player.s: source/entitys/player.cpp.s
.PHONY : source/entitys/player.s

# target to generate assembly for a file
source/entitys/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/player.cpp.s
.PHONY : source/entitys/player.cpp.s

source/entitys/properties/attributes.o: source/entitys/properties/attributes.cpp.o
.PHONY : source/entitys/properties/attributes.o

# target to build an object file
source/entitys/properties/attributes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/properties/attributes.cpp.o
.PHONY : source/entitys/properties/attributes.cpp.o

source/entitys/properties/attributes.i: source/entitys/properties/attributes.cpp.i
.PHONY : source/entitys/properties/attributes.i

# target to preprocess a source file
source/entitys/properties/attributes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/properties/attributes.cpp.i
.PHONY : source/entitys/properties/attributes.cpp.i

source/entitys/properties/attributes.s: source/entitys/properties/attributes.cpp.s
.PHONY : source/entitys/properties/attributes.s

# target to generate assembly for a file
source/entitys/properties/attributes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/properties/attributes.cpp.s
.PHONY : source/entitys/properties/attributes.cpp.s

source/entitys/properties/hitbox.o: source/entitys/properties/hitbox.cpp.o
.PHONY : source/entitys/properties/hitbox.o

# target to build an object file
source/entitys/properties/hitbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/properties/hitbox.cpp.o
.PHONY : source/entitys/properties/hitbox.cpp.o

source/entitys/properties/hitbox.i: source/entitys/properties/hitbox.cpp.i
.PHONY : source/entitys/properties/hitbox.i

# target to preprocess a source file
source/entitys/properties/hitbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/properties/hitbox.cpp.i
.PHONY : source/entitys/properties/hitbox.cpp.i

source/entitys/properties/hitbox.s: source/entitys/properties/hitbox.cpp.s
.PHONY : source/entitys/properties/hitbox.s

# target to generate assembly for a file
source/entitys/properties/hitbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/properties/hitbox.cpp.s
.PHONY : source/entitys/properties/hitbox.cpp.s

source/entitys/properties/movement.o: source/entitys/properties/movement.cpp.o
.PHONY : source/entitys/properties/movement.o

# target to build an object file
source/entitys/properties/movement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/properties/movement.cpp.o
.PHONY : source/entitys/properties/movement.cpp.o

source/entitys/properties/movement.i: source/entitys/properties/movement.cpp.i
.PHONY : source/entitys/properties/movement.i

# target to preprocess a source file
source/entitys/properties/movement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/properties/movement.cpp.i
.PHONY : source/entitys/properties/movement.cpp.i

source/entitys/properties/movement.s: source/entitys/properties/movement.cpp.s
.PHONY : source/entitys/properties/movement.s

# target to generate assembly for a file
source/entitys/properties/movement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/entitys/properties/movement.cpp.s
.PHONY : source/entitys/properties/movement.cpp.s

source/locTexts/helperText.o: source/locTexts/helperText.cpp.o
.PHONY : source/locTexts/helperText.o

# target to build an object file
source/locTexts/helperText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/locTexts/helperText.cpp.o
.PHONY : source/locTexts/helperText.cpp.o

source/locTexts/helperText.i: source/locTexts/helperText.cpp.i
.PHONY : source/locTexts/helperText.i

# target to preprocess a source file
source/locTexts/helperText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/locTexts/helperText.cpp.i
.PHONY : source/locTexts/helperText.cpp.i

source/locTexts/helperText.s: source/locTexts/helperText.cpp.s
.PHONY : source/locTexts/helperText.s

# target to generate assembly for a file
source/locTexts/helperText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/locTexts/helperText.cpp.s
.PHONY : source/locTexts/helperText.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/math/LSystem.o: source/math/LSystem.cpp.o
.PHONY : source/math/LSystem.o

# target to build an object file
source/math/LSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/LSystem.cpp.o
.PHONY : source/math/LSystem.cpp.o

source/math/LSystem.i: source/math/LSystem.cpp.i
.PHONY : source/math/LSystem.i

# target to preprocess a source file
source/math/LSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/LSystem.cpp.i
.PHONY : source/math/LSystem.cpp.i

source/math/LSystem.s: source/math/LSystem.cpp.s
.PHONY : source/math/LSystem.s

# target to generate assembly for a file
source/math/LSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/LSystem.cpp.s
.PHONY : source/math/LSystem.cpp.s

source/math/ProcessGenerationNoice.o: source/math/ProcessGenerationNoice.cpp.o
.PHONY : source/math/ProcessGenerationNoice.o

# target to build an object file
source/math/ProcessGenerationNoice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/ProcessGenerationNoice.cpp.o
.PHONY : source/math/ProcessGenerationNoice.cpp.o

source/math/ProcessGenerationNoice.i: source/math/ProcessGenerationNoice.cpp.i
.PHONY : source/math/ProcessGenerationNoice.i

# target to preprocess a source file
source/math/ProcessGenerationNoice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/ProcessGenerationNoice.cpp.i
.PHONY : source/math/ProcessGenerationNoice.cpp.i

source/math/ProcessGenerationNoice.s: source/math/ProcessGenerationNoice.cpp.s
.PHONY : source/math/ProcessGenerationNoice.s

# target to generate assembly for a file
source/math/ProcessGenerationNoice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/ProcessGenerationNoice.cpp.s
.PHONY : source/math/ProcessGenerationNoice.cpp.s

source/math/mymath.o: source/math/mymath.cpp.o
.PHONY : source/math/mymath.o

# target to build an object file
source/math/mymath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/mymath.cpp.o
.PHONY : source/math/mymath.cpp.o

source/math/mymath.i: source/math/mymath.cpp.i
.PHONY : source/math/mymath.i

# target to preprocess a source file
source/math/mymath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/mymath.cpp.i
.PHONY : source/math/mymath.cpp.i

source/math/mymath.s: source/math/mymath.cpp.s
.PHONY : source/math/mymath.s

# target to generate assembly for a file
source/math/mymath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/mymath.cpp.s
.PHONY : source/math/mymath.cpp.s

source/math/simplex.o: source/math/simplex.cpp.o
.PHONY : source/math/simplex.o

# target to build an object file
source/math/simplex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/simplex.cpp.o
.PHONY : source/math/simplex.cpp.o

source/math/simplex.i: source/math/simplex.cpp.i
.PHONY : source/math/simplex.i

# target to preprocess a source file
source/math/simplex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/simplex.cpp.i
.PHONY : source/math/simplex.cpp.i

source/math/simplex.s: source/math/simplex.cpp.s
.PHONY : source/math/simplex.s

# target to generate assembly for a file
source/math/simplex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/math/simplex.cpp.s
.PHONY : source/math/simplex.cpp.s

source/source/mypars/parsJSON_LOAD.o: source/source/mypars/parsJSON_LOAD.cpp.o
.PHONY : source/source/mypars/parsJSON_LOAD.o

# target to build an object file
source/source/mypars/parsJSON_LOAD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/source/mypars/parsJSON_LOAD.cpp.o
.PHONY : source/source/mypars/parsJSON_LOAD.cpp.o

source/source/mypars/parsJSON_LOAD.i: source/source/mypars/parsJSON_LOAD.cpp.i
.PHONY : source/source/mypars/parsJSON_LOAD.i

# target to preprocess a source file
source/source/mypars/parsJSON_LOAD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/source/mypars/parsJSON_LOAD.cpp.i
.PHONY : source/source/mypars/parsJSON_LOAD.cpp.i

source/source/mypars/parsJSON_LOAD.s: source/source/mypars/parsJSON_LOAD.cpp.s
.PHONY : source/source/mypars/parsJSON_LOAD.s

# target to generate assembly for a file
source/source/mypars/parsJSON_LOAD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/source/mypars/parsJSON_LOAD.cpp.s
.PHONY : source/source/mypars/parsJSON_LOAD.cpp.s

source/source/mypars/parsJSON_SAVE.o: source/source/mypars/parsJSON_SAVE.cpp.o
.PHONY : source/source/mypars/parsJSON_SAVE.o

# target to build an object file
source/source/mypars/parsJSON_SAVE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/source/mypars/parsJSON_SAVE.cpp.o
.PHONY : source/source/mypars/parsJSON_SAVE.cpp.o

source/source/mypars/parsJSON_SAVE.i: source/source/mypars/parsJSON_SAVE.cpp.i
.PHONY : source/source/mypars/parsJSON_SAVE.i

# target to preprocess a source file
source/source/mypars/parsJSON_SAVE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/source/mypars/parsJSON_SAVE.cpp.i
.PHONY : source/source/mypars/parsJSON_SAVE.cpp.i

source/source/mypars/parsJSON_SAVE.s: source/source/mypars/parsJSON_SAVE.cpp.s
.PHONY : source/source/mypars/parsJSON_SAVE.s

# target to generate assembly for a file
source/source/mypars/parsJSON_SAVE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/source/mypars/parsJSON_SAVE.cpp.s
.PHONY : source/source/mypars/parsJSON_SAVE.cpp.s

source/states/EditorState.o: source/states/EditorState.cpp.o
.PHONY : source/states/EditorState.o

# target to build an object file
source/states/EditorState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/EditorState.cpp.o
.PHONY : source/states/EditorState.cpp.o

source/states/EditorState.i: source/states/EditorState.cpp.i
.PHONY : source/states/EditorState.i

# target to preprocess a source file
source/states/EditorState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/EditorState.cpp.i
.PHONY : source/states/EditorState.cpp.i

source/states/EditorState.s: source/states/EditorState.cpp.s
.PHONY : source/states/EditorState.s

# target to generate assembly for a file
source/states/EditorState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/EditorState.cpp.s
.PHONY : source/states/EditorState.cpp.s

source/states/MainMenu.o: source/states/MainMenu.cpp.o
.PHONY : source/states/MainMenu.o

# target to build an object file
source/states/MainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/MainMenu.cpp.o
.PHONY : source/states/MainMenu.cpp.o

source/states/MainMenu.i: source/states/MainMenu.cpp.i
.PHONY : source/states/MainMenu.i

# target to preprocess a source file
source/states/MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/MainMenu.cpp.i
.PHONY : source/states/MainMenu.cpp.i

source/states/MainMenu.s: source/states/MainMenu.cpp.s
.PHONY : source/states/MainMenu.s

# target to generate assembly for a file
source/states/MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/MainMenu.cpp.s
.PHONY : source/states/MainMenu.cpp.s

source/states/PauseMenu.o: source/states/PauseMenu.cpp.o
.PHONY : source/states/PauseMenu.o

# target to build an object file
source/states/PauseMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/PauseMenu.cpp.o
.PHONY : source/states/PauseMenu.cpp.o

source/states/PauseMenu.i: source/states/PauseMenu.cpp.i
.PHONY : source/states/PauseMenu.i

# target to preprocess a source file
source/states/PauseMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/PauseMenu.cpp.i
.PHONY : source/states/PauseMenu.cpp.i

source/states/PauseMenu.s: source/states/PauseMenu.cpp.s
.PHONY : source/states/PauseMenu.s

# target to generate assembly for a file
source/states/PauseMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/PauseMenu.cpp.s
.PHONY : source/states/PauseMenu.cpp.s

source/states/Process.o: source/states/Process.cpp.o
.PHONY : source/states/Process.o

# target to build an object file
source/states/Process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/Process.cpp.o
.PHONY : source/states/Process.cpp.o

source/states/Process.i: source/states/Process.cpp.i
.PHONY : source/states/Process.i

# target to preprocess a source file
source/states/Process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/Process.cpp.i
.PHONY : source/states/Process.cpp.i

source/states/Process.s: source/states/Process.cpp.s
.PHONY : source/states/Process.s

# target to generate assembly for a file
source/states/Process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/Process.cpp.s
.PHONY : source/states/Process.cpp.s

source/states/State.o: source/states/State.cpp.o
.PHONY : source/states/State.o

# target to build an object file
source/states/State.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/State.cpp.o
.PHONY : source/states/State.cpp.o

source/states/State.i: source/states/State.cpp.i
.PHONY : source/states/State.i

# target to preprocess a source file
source/states/State.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/State.cpp.i
.PHONY : source/states/State.cpp.i

source/states/State.s: source/states/State.cpp.s
.PHONY : source/states/State.s

# target to generate assembly for a file
source/states/State.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/State.cpp.s
.PHONY : source/states/State.cpp.s

source/states/editModes/NoiceViewer.o: source/states/editModes/NoiceViewer.cpp.o
.PHONY : source/states/editModes/NoiceViewer.o

# target to build an object file
source/states/editModes/NoiceViewer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/editModes/NoiceViewer.cpp.o
.PHONY : source/states/editModes/NoiceViewer.cpp.o

source/states/editModes/NoiceViewer.i: source/states/editModes/NoiceViewer.cpp.i
.PHONY : source/states/editModes/NoiceViewer.i

# target to preprocess a source file
source/states/editModes/NoiceViewer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/editModes/NoiceViewer.cpp.i
.PHONY : source/states/editModes/NoiceViewer.cpp.i

source/states/editModes/NoiceViewer.s: source/states/editModes/NoiceViewer.cpp.s
.PHONY : source/states/editModes/NoiceViewer.s

# target to generate assembly for a file
source/states/editModes/NoiceViewer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/editModes/NoiceViewer.cpp.s
.PHONY : source/states/editModes/NoiceViewer.cpp.s

source/states/settings.o: source/states/settings.cpp.o
.PHONY : source/states/settings.o

# target to build an object file
source/states/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/settings.cpp.o
.PHONY : source/states/settings.cpp.o

source/states/settings.i: source/states/settings.cpp.i
.PHONY : source/states/settings.i

# target to preprocess a source file
source/states/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/settings.cpp.i
.PHONY : source/states/settings.cpp.i

source/states/settings.s: source/states/settings.cpp.s
.PHONY : source/states/settings.s

# target to generate assembly for a file
source/states/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ekzeckt.dir/build.make CMakeFiles/Ekzeckt.dir/source/states/settings.cpp.s
.PHONY : source/states/settings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... Ekzeckt"
	@echo "... source/Content/ItemsStuff/Inventory.o"
	@echo "... source/Content/ItemsStuff/Inventory.i"
	@echo "... source/Content/ItemsStuff/Inventory.s"
	@echo "... source/Content/Map/TileMap.o"
	@echo "... source/Content/Map/TileMap.i"
	@echo "... source/Content/Map/TileMap.s"
	@echo "... source/Content/Map/block.o"
	@echo "... source/Content/Map/block.i"
	@echo "... source/Content/Map/block.s"
	@echo "... source/Content/rotationCircle.o"
	@echo "... source/Content/rotationCircle.i"
	@echo "... source/Content/rotationCircle.s"
	@echo "... source/Core.o"
	@echo "... source/Core.i"
	@echo "... source/Core.s"
	@echo "... source/GUI/components/button.o"
	@echo "... source/GUI/components/button.i"
	@echo "... source/GUI/components/button.s"
	@echo "... source/GUI/components/dropDownList.o"
	@echo "... source/GUI/components/dropDownList.i"
	@echo "... source/GUI/components/dropDownList.s"
	@echo "... source/GUI/components/minimap.o"
	@echo "... source/GUI/components/minimap.i"
	@echo "... source/GUI/components/minimap.s"
	@echo "... source/GUI/components/progressBar.o"
	@echo "... source/GUI/components/progressBar.i"
	@echo "... source/GUI/components/progressBar.s"
	@echo "... source/GUI/components/selector.o"
	@echo "... source/GUI/components/selector.i"
	@echo "... source/GUI/components/selector.s"
	@echo "... source/GUI/components/staticSelector.o"
	@echo "... source/GUI/components/staticSelector.i"
	@echo "... source/GUI/components/staticSelector.s"
	@echo "... source/GUI/components/textbox.o"
	@echo "... source/GUI/components/textbox.i"
	@echo "... source/GUI/components/textbox.s"
	@echo "... source/GUI/components/textureSelector.o"
	@echo "... source/GUI/components/textureSelector.i"
	@echo "... source/GUI/components/textureSelector.s"
	@echo "... source/entitys/AI/AIAttack.o"
	@echo "... source/entitys/AI/AIAttack.i"
	@echo "... source/entitys/AI/AIAttack.s"
	@echo "... source/entitys/AI/AIComponent.o"
	@echo "... source/entitys/AI/AIComponent.i"
	@echo "... source/entitys/AI/AIComponent.s"
	@echo "... source/entitys/AI/AIFollow.o"
	@echo "... source/entitys/AI/AIFollow.i"
	@echo "... source/entitys/AI/AIFollow.s"
	@echo "... source/entitys/AI/AISearchRing.o"
	@echo "... source/entitys/AI/AISearchRing.i"
	@echo "... source/entitys/AI/AISearchRing.s"
	@echo "... source/entitys/AI/AIWander.o"
	@echo "... source/entitys/AI/AIWander.i"
	@echo "... source/entitys/AI/AIWander.s"
	@echo "... source/entitys/Enemys/slime.o"
	@echo "... source/entitys/Enemys/slime.i"
	@echo "... source/entitys/Enemys/slime.s"
	@echo "... source/entitys/entity.o"
	@echo "... source/entitys/entity.i"
	@echo "... source/entitys/entity.s"
	@echo "... source/entitys/player.o"
	@echo "... source/entitys/player.i"
	@echo "... source/entitys/player.s"
	@echo "... source/entitys/properties/attributes.o"
	@echo "... source/entitys/properties/attributes.i"
	@echo "... source/entitys/properties/attributes.s"
	@echo "... source/entitys/properties/hitbox.o"
	@echo "... source/entitys/properties/hitbox.i"
	@echo "... source/entitys/properties/hitbox.s"
	@echo "... source/entitys/properties/movement.o"
	@echo "... source/entitys/properties/movement.i"
	@echo "... source/entitys/properties/movement.s"
	@echo "... source/locTexts/helperText.o"
	@echo "... source/locTexts/helperText.i"
	@echo "... source/locTexts/helperText.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/math/LSystem.o"
	@echo "... source/math/LSystem.i"
	@echo "... source/math/LSystem.s"
	@echo "... source/math/ProcessGenerationNoice.o"
	@echo "... source/math/ProcessGenerationNoice.i"
	@echo "... source/math/ProcessGenerationNoice.s"
	@echo "... source/math/mymath.o"
	@echo "... source/math/mymath.i"
	@echo "... source/math/mymath.s"
	@echo "... source/math/simplex.o"
	@echo "... source/math/simplex.i"
	@echo "... source/math/simplex.s"
	@echo "... source/source/mypars/parsJSON_LOAD.o"
	@echo "... source/source/mypars/parsJSON_LOAD.i"
	@echo "... source/source/mypars/parsJSON_LOAD.s"
	@echo "... source/source/mypars/parsJSON_SAVE.o"
	@echo "... source/source/mypars/parsJSON_SAVE.i"
	@echo "... source/source/mypars/parsJSON_SAVE.s"
	@echo "... source/states/EditorState.o"
	@echo "... source/states/EditorState.i"
	@echo "... source/states/EditorState.s"
	@echo "... source/states/MainMenu.o"
	@echo "... source/states/MainMenu.i"
	@echo "... source/states/MainMenu.s"
	@echo "... source/states/PauseMenu.o"
	@echo "... source/states/PauseMenu.i"
	@echo "... source/states/PauseMenu.s"
	@echo "... source/states/Process.o"
	@echo "... source/states/Process.i"
	@echo "... source/states/Process.s"
	@echo "... source/states/State.o"
	@echo "... source/states/State.i"
	@echo "... source/states/State.s"
	@echo "... source/states/editModes/NoiceViewer.o"
	@echo "... source/states/editModes/NoiceViewer.i"
	@echo "... source/states/editModes/NoiceViewer.s"
	@echo "... source/states/settings.o"
	@echo "... source/states/settings.i"
	@echo "... source/states/settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

