#ifndef PROJ_VER
#define PROJ_VER

#define CMAKE_PROJECT_VERSION 0.0.3
/* #undef CMAKE_PROJECT_VERSION_MAJOR */
/* #undef CMAKE_PROJECT_VERSION_MINOR */
#define CMAKE_PROJECT_VERSION_PATCH 3


#endif
